/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as StoreRouteImport } from './routes/store'
import { Route as ElectionsRouteImport } from './routes/elections'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VoteReceiptAuditRouteImport } from './routes/vote/receipt-audit'
import { Route as VoteElectionRouteImport } from './routes/vote/election'
import { Route as VoteCastRouteImport } from './routes/vote/cast'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthSigninRouteImport } from './routes/auth.signin'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminPublicRouteImport } from './routes/admin/public'
import { Route as NomineeNomineeIdIndexRouteImport } from './routes/nominee/$nomineeId/index'
import { Route as EventsEventIdIndexRouteImport } from './routes/events/$eventId/index'
import { Route as AdminVotersIndexRouteImport } from './routes/admin/voters.index'
import { Route as AdminPositionsIndexRouteImport } from './routes/admin/positions.index'
import { Route as AdminOrganizationsIndexRouteImport } from './routes/admin/organizations.index'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events.index'
import { Route as AdminElectionsIndexRouteImport } from './routes/admin/elections.index'
import { Route as AdminContestantsIndexRouteImport } from './routes/admin/contestants.index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories.index'
import { Route as AdminCandidatesIndexRouteImport } from './routes/admin/candidates.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AdminVotersNewRouteImport } from './routes/admin/voters.new'
import { Route as AdminPositionsNewRouteImport } from './routes/admin/positions.new'
import { Route as AdminOrganizationsNewRouteImport } from './routes/admin/organizations.new'
import { Route as AdminEventsNewRouteImport } from './routes/admin/events.new'
import { Route as AdminEventsManageRouteImport } from './routes/admin/events.manage'
import { Route as AdminEventsFeedRouteImport } from './routes/admin/events.feed'
import { Route as AdminElectionsNewRouteImport } from './routes/admin/elections.new'
import { Route as AdminContestantsNewRouteImport } from './routes/admin/contestants.new'
import { Route as AdminCategoriesNewRouteImport } from './routes/admin/categories.new'
import { Route as AdminCandidatesNewRouteImport } from './routes/admin/candidates.new'
import { Route as EventsEventIdCategoriesIndexRouteImport } from './routes/events/$eventId/categories/index'
import { Route as AdminVotersVoterIdEditRouteImport } from './routes/admin/voters.$voterId.edit'
import { Route as AdminPositionsPositionIdEditRouteImport } from './routes/admin/positions.$positionId.edit'
import { Route as AdminElectionsElectionIdManageRouteImport } from './routes/admin/elections.$electionId.manage'
import { Route as AdminElectionsElectionIdFeedRouteImport } from './routes/admin/elections.$electionId.feed'
import { Route as AdminElectionsElectionIdEditRouteImport } from './routes/admin/elections.$electionId.edit'
import { Route as AdminCandidatesCandidateIdEditRouteImport } from './routes/admin/candidates.$candidateId.edit'
import { Route as EventsEventIdCategoriesCategoryIdIndexRouteImport } from './routes/events/$eventId/categories/$categoryId/index'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectionsRoute = ElectionsRouteImport.update({
  id: '/elections',
  path: '/elections',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const VoteReceiptAuditRoute = VoteReceiptAuditRouteImport.update({
  id: '/vote/receipt-audit',
  path: '/vote/receipt-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteElectionRoute = VoteElectionRouteImport.update({
  id: '/vote/election',
  path: '/vote/election',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteCastRoute = VoteCastRouteImport.update({
  id: '/vote/cast',
  path: '/vote/cast',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPublicRoute = AdminPublicRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => AdminRouteRoute,
} as any)
const NomineeNomineeIdIndexRoute = NomineeNomineeIdIndexRouteImport.update({
  id: '/nominee/$nomineeId/',
  path: '/nominee/$nomineeId/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVotersIndexRoute = AdminVotersIndexRouteImport.update({
  id: '/voters/',
  path: '/voters/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPositionsIndexRoute = AdminPositionsIndexRouteImport.update({
  id: '/positions/',
  path: '/positions/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationsIndexRoute = AdminOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminElectionsIndexRoute = AdminElectionsIndexRouteImport.update({
  id: '/elections/',
  path: '/elections/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContestantsIndexRoute = AdminContestantsIndexRouteImport.update({
  id: '/contestants/',
  path: '/contestants/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCandidatesIndexRoute = AdminCandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVotersNewRoute = AdminVotersNewRouteImport.update({
  id: '/voters/new',
  path: '/voters/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPositionsNewRoute = AdminPositionsNewRouteImport.update({
  id: '/positions/new',
  path: '/positions/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationsNewRoute = AdminOrganizationsNewRouteImport.update({
  id: '/organizations/new',
  path: '/organizations/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsNewRoute = AdminEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsManageRoute = AdminEventsManageRouteImport.update({
  id: '/events/manage',
  path: '/events/manage',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsFeedRoute = AdminEventsFeedRouteImport.update({
  id: '/events/feed',
  path: '/events/feed',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminElectionsNewRoute = AdminElectionsNewRouteImport.update({
  id: '/elections/new',
  path: '/elections/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContestantsNewRoute = AdminContestantsNewRouteImport.update({
  id: '/contestants/new',
  path: '/contestants/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesNewRoute = AdminCategoriesNewRouteImport.update({
  id: '/categories/new',
  path: '/categories/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCandidatesNewRoute = AdminCandidatesNewRouteImport.update({
  id: '/candidates/new',
  path: '/candidates/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const EventsEventIdCategoriesIndexRoute =
  EventsEventIdCategoriesIndexRouteImport.update({
    id: '/events/$eventId/categories/',
    path: '/events/$eventId/categories/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminVotersVoterIdEditRoute = AdminVotersVoterIdEditRouteImport.update({
  id: '/voters/$voterId/edit',
  path: '/voters/$voterId/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPositionsPositionIdEditRoute =
  AdminPositionsPositionIdEditRouteImport.update({
    id: '/positions/$positionId/edit',
    path: '/positions/$positionId/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminElectionsElectionIdManageRoute =
  AdminElectionsElectionIdManageRouteImport.update({
    id: '/elections/$electionId/manage',
    path: '/elections/$electionId/manage',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminElectionsElectionIdFeedRoute =
  AdminElectionsElectionIdFeedRouteImport.update({
    id: '/elections/$electionId/feed',
    path: '/elections/$electionId/feed',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminElectionsElectionIdEditRoute =
  AdminElectionsElectionIdEditRouteImport.update({
    id: '/elections/$electionId/edit',
    path: '/elections/$electionId/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCandidatesCandidateIdEditRoute =
  AdminCandidatesCandidateIdEditRouteImport.update({
    id: '/candidates/$candidateId/edit',
    path: '/candidates/$candidateId/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const EventsEventIdCategoriesCategoryIdIndexRoute =
  EventsEventIdCategoriesCategoryIdIndexRouteImport.update({
    id: '/events/$eventId/categories/$categoryId/',
    path: '/events/$eventId/categories/$categoryId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/elections': typeof ElectionsRoute
  '/store': typeof StoreRoute
  '/tickets': typeof TicketsRoute
  '/admin/public': typeof AdminPublicRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/vote/cast': typeof VoteCastRoute
  '/vote/election': typeof VoteElectionRoute
  '/vote/receipt-audit': typeof VoteReceiptAuditRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/admin/candidates/new': typeof AdminCandidatesNewRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/contestants/new': typeof AdminContestantsNewRoute
  '/admin/elections/new': typeof AdminElectionsNewRoute
  '/admin/events/feed': typeof AdminEventsFeedRoute
  '/admin/events/manage': typeof AdminEventsManageRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/organizations/new': typeof AdminOrganizationsNewRoute
  '/admin/positions/new': typeof AdminPositionsNewRoute
  '/admin/voters/new': typeof AdminVotersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/candidates/': typeof AdminCandidatesIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/contestants/': typeof AdminContestantsIndexRoute
  '/admin/elections/': typeof AdminElectionsIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/admin/positions/': typeof AdminPositionsIndexRoute
  '/admin/voters/': typeof AdminVotersIndexRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/nominee/$nomineeId/': typeof NomineeNomineeIdIndexRoute
  '/admin/candidates/$candidateId/edit': typeof AdminCandidatesCandidateIdEditRoute
  '/admin/elections/$electionId/edit': typeof AdminElectionsElectionIdEditRoute
  '/admin/elections/$electionId/feed': typeof AdminElectionsElectionIdFeedRoute
  '/admin/elections/$electionId/manage': typeof AdminElectionsElectionIdManageRoute
  '/admin/positions/$positionId/edit': typeof AdminPositionsPositionIdEditRoute
  '/admin/voters/$voterId/edit': typeof AdminVotersVoterIdEditRoute
  '/events/$eventId/categories/': typeof EventsEventIdCategoriesIndexRoute
  '/events/$eventId/categories/$categoryId/': typeof EventsEventIdCategoriesCategoryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/elections': typeof ElectionsRoute
  '/store': typeof StoreRoute
  '/tickets': typeof TicketsRoute
  '/admin/public': typeof AdminPublicRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/vote/cast': typeof VoteCastRoute
  '/vote/election': typeof VoteElectionRoute
  '/vote/receipt-audit': typeof VoteReceiptAuditRoute
  '/admin': typeof AdminIndexRoute
  '/events': typeof EventsIndexRoute
  '/admin/candidates/new': typeof AdminCandidatesNewRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/contestants/new': typeof AdminContestantsNewRoute
  '/admin/elections/new': typeof AdminElectionsNewRoute
  '/admin/events/feed': typeof AdminEventsFeedRoute
  '/admin/events/manage': typeof AdminEventsManageRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/organizations/new': typeof AdminOrganizationsNewRoute
  '/admin/positions/new': typeof AdminPositionsNewRoute
  '/admin/voters/new': typeof AdminVotersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/candidates': typeof AdminCandidatesIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/contestants': typeof AdminContestantsIndexRoute
  '/admin/elections': typeof AdminElectionsIndexRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/organizations': typeof AdminOrganizationsIndexRoute
  '/admin/positions': typeof AdminPositionsIndexRoute
  '/admin/voters': typeof AdminVotersIndexRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
  '/nominee/$nomineeId': typeof NomineeNomineeIdIndexRoute
  '/admin/candidates/$candidateId/edit': typeof AdminCandidatesCandidateIdEditRoute
  '/admin/elections/$electionId/edit': typeof AdminElectionsElectionIdEditRoute
  '/admin/elections/$electionId/feed': typeof AdminElectionsElectionIdFeedRoute
  '/admin/elections/$electionId/manage': typeof AdminElectionsElectionIdManageRoute
  '/admin/positions/$positionId/edit': typeof AdminPositionsPositionIdEditRoute
  '/admin/voters/$voterId/edit': typeof AdminVotersVoterIdEditRoute
  '/events/$eventId/categories': typeof EventsEventIdCategoriesIndexRoute
  '/events/$eventId/categories/$categoryId': typeof EventsEventIdCategoriesCategoryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/elections': typeof ElectionsRoute
  '/store': typeof StoreRoute
  '/tickets': typeof TicketsRoute
  '/admin/public': typeof AdminPublicRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/vote/cast': typeof VoteCastRoute
  '/vote/election': typeof VoteElectionRoute
  '/vote/receipt-audit': typeof VoteReceiptAuditRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/admin/candidates/new': typeof AdminCandidatesNewRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/contestants/new': typeof AdminContestantsNewRoute
  '/admin/elections/new': typeof AdminElectionsNewRoute
  '/admin/events/feed': typeof AdminEventsFeedRoute
  '/admin/events/manage': typeof AdminEventsManageRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/organizations/new': typeof AdminOrganizationsNewRoute
  '/admin/positions/new': typeof AdminPositionsNewRoute
  '/admin/voters/new': typeof AdminVotersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/candidates/': typeof AdminCandidatesIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/contestants/': typeof AdminContestantsIndexRoute
  '/admin/elections/': typeof AdminElectionsIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/admin/positions/': typeof AdminPositionsIndexRoute
  '/admin/voters/': typeof AdminVotersIndexRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/nominee/$nomineeId/': typeof NomineeNomineeIdIndexRoute
  '/admin/candidates/$candidateId/edit': typeof AdminCandidatesCandidateIdEditRoute
  '/admin/elections/$electionId/edit': typeof AdminElectionsElectionIdEditRoute
  '/admin/elections/$electionId/feed': typeof AdminElectionsElectionIdFeedRoute
  '/admin/elections/$electionId/manage': typeof AdminElectionsElectionIdManageRoute
  '/admin/positions/$positionId/edit': typeof AdminPositionsPositionIdEditRoute
  '/admin/voters/$voterId/edit': typeof AdminVotersVoterIdEditRoute
  '/events/$eventId/categories/': typeof EventsEventIdCategoriesIndexRoute
  '/events/$eventId/categories/$categoryId/': typeof EventsEventIdCategoriesCategoryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/blog'
    | '/contact'
    | '/elections'
    | '/store'
    | '/tickets'
    | '/admin/public'
    | '/admin/settings'
    | '/auth/signin'
    | '/auth/signup'
    | '/vote/cast'
    | '/vote/election'
    | '/vote/receipt-audit'
    | '/admin/'
    | '/events/'
    | '/admin/candidates/new'
    | '/admin/categories/new'
    | '/admin/contestants/new'
    | '/admin/elections/new'
    | '/admin/events/feed'
    | '/admin/events/manage'
    | '/admin/events/new'
    | '/admin/organizations/new'
    | '/admin/positions/new'
    | '/admin/voters/new'
    | '/api/auth/$'
    | '/admin/candidates/'
    | '/admin/categories/'
    | '/admin/contestants/'
    | '/admin/elections/'
    | '/admin/events/'
    | '/admin/organizations/'
    | '/admin/positions/'
    | '/admin/voters/'
    | '/events/$eventId/'
    | '/nominee/$nomineeId/'
    | '/admin/candidates/$candidateId/edit'
    | '/admin/elections/$electionId/edit'
    | '/admin/elections/$electionId/feed'
    | '/admin/elections/$electionId/manage'
    | '/admin/positions/$positionId/edit'
    | '/admin/voters/$voterId/edit'
    | '/events/$eventId/categories/'
    | '/events/$eventId/categories/$categoryId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/elections'
    | '/store'
    | '/tickets'
    | '/admin/public'
    | '/admin/settings'
    | '/auth/signin'
    | '/auth/signup'
    | '/vote/cast'
    | '/vote/election'
    | '/vote/receipt-audit'
    | '/admin'
    | '/events'
    | '/admin/candidates/new'
    | '/admin/categories/new'
    | '/admin/contestants/new'
    | '/admin/elections/new'
    | '/admin/events/feed'
    | '/admin/events/manage'
    | '/admin/events/new'
    | '/admin/organizations/new'
    | '/admin/positions/new'
    | '/admin/voters/new'
    | '/api/auth/$'
    | '/admin/candidates'
    | '/admin/categories'
    | '/admin/contestants'
    | '/admin/elections'
    | '/admin/events'
    | '/admin/organizations'
    | '/admin/positions'
    | '/admin/voters'
    | '/events/$eventId'
    | '/nominee/$nomineeId'
    | '/admin/candidates/$candidateId/edit'
    | '/admin/elections/$electionId/edit'
    | '/admin/elections/$electionId/feed'
    | '/admin/elections/$electionId/manage'
    | '/admin/positions/$positionId/edit'
    | '/admin/voters/$voterId/edit'
    | '/events/$eventId/categories'
    | '/events/$eventId/categories/$categoryId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/blog'
    | '/contact'
    | '/elections'
    | '/store'
    | '/tickets'
    | '/admin/public'
    | '/admin/settings'
    | '/auth/signin'
    | '/auth/signup'
    | '/vote/cast'
    | '/vote/election'
    | '/vote/receipt-audit'
    | '/admin/'
    | '/events/'
    | '/admin/candidates/new'
    | '/admin/categories/new'
    | '/admin/contestants/new'
    | '/admin/elections/new'
    | '/admin/events/feed'
    | '/admin/events/manage'
    | '/admin/events/new'
    | '/admin/organizations/new'
    | '/admin/positions/new'
    | '/admin/voters/new'
    | '/api/auth/$'
    | '/admin/candidates/'
    | '/admin/categories/'
    | '/admin/contestants/'
    | '/admin/elections/'
    | '/admin/events/'
    | '/admin/organizations/'
    | '/admin/positions/'
    | '/admin/voters/'
    | '/events/$eventId/'
    | '/nominee/$nomineeId/'
    | '/admin/candidates/$candidateId/edit'
    | '/admin/elections/$electionId/edit'
    | '/admin/elections/$electionId/feed'
    | '/admin/elections/$electionId/manage'
    | '/admin/positions/$positionId/edit'
    | '/admin/voters/$voterId/edit'
    | '/events/$eventId/categories/'
    | '/events/$eventId/categories/$categoryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  ElectionsRoute: typeof ElectionsRoute
  StoreRoute: typeof StoreRoute
  TicketsRoute: typeof TicketsRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  VoteCastRoute: typeof VoteCastRoute
  VoteElectionRoute: typeof VoteElectionRoute
  VoteReceiptAuditRoute: typeof VoteReceiptAuditRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
  NomineeNomineeIdIndexRoute: typeof NomineeNomineeIdIndexRoute
  EventsEventIdCategoriesIndexRoute: typeof EventsEventIdCategoriesIndexRoute
  EventsEventIdCategoriesCategoryIdIndexRoute: typeof EventsEventIdCategoriesCategoryIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elections': {
      id: '/elections'
      path: '/elections'
      fullPath: '/elections'
      preLoaderRoute: typeof ElectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/vote/receipt-audit': {
      id: '/vote/receipt-audit'
      path: '/vote/receipt-audit'
      fullPath: '/vote/receipt-audit'
      preLoaderRoute: typeof VoteReceiptAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote/election': {
      id: '/vote/election'
      path: '/vote/election'
      fullPath: '/vote/election'
      preLoaderRoute: typeof VoteElectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote/cast': {
      id: '/vote/cast'
      path: '/vote/cast'
      fullPath: '/vote/cast'
      preLoaderRoute: typeof VoteCastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/public': {
      id: '/admin/public'
      path: '/public'
      fullPath: '/admin/public'
      preLoaderRoute: typeof AdminPublicRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/nominee/$nomineeId/': {
      id: '/nominee/$nomineeId/'
      path: '/nominee/$nomineeId'
      fullPath: '/nominee/$nomineeId/'
      preLoaderRoute: typeof NomineeNomineeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/voters/': {
      id: '/admin/voters/'
      path: '/voters'
      fullPath: '/admin/voters/'
      preLoaderRoute: typeof AdminVotersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/positions/': {
      id: '/admin/positions/'
      path: '/positions'
      fullPath: '/admin/positions/'
      preLoaderRoute: typeof AdminPositionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organizations/': {
      id: '/admin/organizations/'
      path: '/organizations'
      fullPath: '/admin/organizations/'
      preLoaderRoute: typeof AdminOrganizationsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/elections/': {
      id: '/admin/elections/'
      path: '/elections'
      fullPath: '/admin/elections/'
      preLoaderRoute: typeof AdminElectionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contestants/': {
      id: '/admin/contestants/'
      path: '/contestants'
      fullPath: '/admin/contestants/'
      preLoaderRoute: typeof AdminContestantsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/candidates/': {
      id: '/admin/candidates/'
      path: '/candidates'
      fullPath: '/admin/candidates/'
      preLoaderRoute: typeof AdminCandidatesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/voters/new': {
      id: '/admin/voters/new'
      path: '/voters/new'
      fullPath: '/admin/voters/new'
      preLoaderRoute: typeof AdminVotersNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/positions/new': {
      id: '/admin/positions/new'
      path: '/positions/new'
      fullPath: '/admin/positions/new'
      preLoaderRoute: typeof AdminPositionsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organizations/new': {
      id: '/admin/organizations/new'
      path: '/organizations/new'
      fullPath: '/admin/organizations/new'
      preLoaderRoute: typeof AdminOrganizationsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events/new': {
      id: '/admin/events/new'
      path: '/events/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AdminEventsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events/manage': {
      id: '/admin/events/manage'
      path: '/events/manage'
      fullPath: '/admin/events/manage'
      preLoaderRoute: typeof AdminEventsManageRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events/feed': {
      id: '/admin/events/feed'
      path: '/events/feed'
      fullPath: '/admin/events/feed'
      preLoaderRoute: typeof AdminEventsFeedRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/elections/new': {
      id: '/admin/elections/new'
      path: '/elections/new'
      fullPath: '/admin/elections/new'
      preLoaderRoute: typeof AdminElectionsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contestants/new': {
      id: '/admin/contestants/new'
      path: '/contestants/new'
      fullPath: '/admin/contestants/new'
      preLoaderRoute: typeof AdminContestantsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories/new': {
      id: '/admin/categories/new'
      path: '/categories/new'
      fullPath: '/admin/categories/new'
      preLoaderRoute: typeof AdminCategoriesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/candidates/new': {
      id: '/admin/candidates/new'
      path: '/candidates/new'
      fullPath: '/admin/candidates/new'
      preLoaderRoute: typeof AdminCandidatesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/events/$eventId/categories/': {
      id: '/events/$eventId/categories/'
      path: '/events/$eventId/categories'
      fullPath: '/events/$eventId/categories/'
      preLoaderRoute: typeof EventsEventIdCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/voters/$voterId/edit': {
      id: '/admin/voters/$voterId/edit'
      path: '/voters/$voterId/edit'
      fullPath: '/admin/voters/$voterId/edit'
      preLoaderRoute: typeof AdminVotersVoterIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/positions/$positionId/edit': {
      id: '/admin/positions/$positionId/edit'
      path: '/positions/$positionId/edit'
      fullPath: '/admin/positions/$positionId/edit'
      preLoaderRoute: typeof AdminPositionsPositionIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/elections/$electionId/manage': {
      id: '/admin/elections/$electionId/manage'
      path: '/elections/$electionId/manage'
      fullPath: '/admin/elections/$electionId/manage'
      preLoaderRoute: typeof AdminElectionsElectionIdManageRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/elections/$electionId/feed': {
      id: '/admin/elections/$electionId/feed'
      path: '/elections/$electionId/feed'
      fullPath: '/admin/elections/$electionId/feed'
      preLoaderRoute: typeof AdminElectionsElectionIdFeedRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/elections/$electionId/edit': {
      id: '/admin/elections/$electionId/edit'
      path: '/elections/$electionId/edit'
      fullPath: '/admin/elections/$electionId/edit'
      preLoaderRoute: typeof AdminElectionsElectionIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/candidates/$candidateId/edit': {
      id: '/admin/candidates/$candidateId/edit'
      path: '/candidates/$candidateId/edit'
      fullPath: '/admin/candidates/$candidateId/edit'
      preLoaderRoute: typeof AdminCandidatesCandidateIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/events/$eventId/categories/$categoryId/': {
      id: '/events/$eventId/categories/$categoryId/'
      path: '/events/$eventId/categories/$categoryId'
      fullPath: '/events/$eventId/categories/$categoryId/'
      preLoaderRoute: typeof EventsEventIdCategoriesCategoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminPublicRoute: typeof AdminPublicRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCandidatesNewRoute: typeof AdminCandidatesNewRoute
  AdminCategoriesNewRoute: typeof AdminCategoriesNewRoute
  AdminContestantsNewRoute: typeof AdminContestantsNewRoute
  AdminElectionsNewRoute: typeof AdminElectionsNewRoute
  AdminEventsFeedRoute: typeof AdminEventsFeedRoute
  AdminEventsManageRoute: typeof AdminEventsManageRoute
  AdminEventsNewRoute: typeof AdminEventsNewRoute
  AdminOrganizationsNewRoute: typeof AdminOrganizationsNewRoute
  AdminPositionsNewRoute: typeof AdminPositionsNewRoute
  AdminVotersNewRoute: typeof AdminVotersNewRoute
  AdminCandidatesIndexRoute: typeof AdminCandidatesIndexRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminContestantsIndexRoute: typeof AdminContestantsIndexRoute
  AdminElectionsIndexRoute: typeof AdminElectionsIndexRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminOrganizationsIndexRoute: typeof AdminOrganizationsIndexRoute
  AdminPositionsIndexRoute: typeof AdminPositionsIndexRoute
  AdminVotersIndexRoute: typeof AdminVotersIndexRoute
  AdminCandidatesCandidateIdEditRoute: typeof AdminCandidatesCandidateIdEditRoute
  AdminElectionsElectionIdEditRoute: typeof AdminElectionsElectionIdEditRoute
  AdminElectionsElectionIdFeedRoute: typeof AdminElectionsElectionIdFeedRoute
  AdminElectionsElectionIdManageRoute: typeof AdminElectionsElectionIdManageRoute
  AdminPositionsPositionIdEditRoute: typeof AdminPositionsPositionIdEditRoute
  AdminVotersVoterIdEditRoute: typeof AdminVotersVoterIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminPublicRoute: AdminPublicRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCandidatesNewRoute: AdminCandidatesNewRoute,
  AdminCategoriesNewRoute: AdminCategoriesNewRoute,
  AdminContestantsNewRoute: AdminContestantsNewRoute,
  AdminElectionsNewRoute: AdminElectionsNewRoute,
  AdminEventsFeedRoute: AdminEventsFeedRoute,
  AdminEventsManageRoute: AdminEventsManageRoute,
  AdminEventsNewRoute: AdminEventsNewRoute,
  AdminOrganizationsNewRoute: AdminOrganizationsNewRoute,
  AdminPositionsNewRoute: AdminPositionsNewRoute,
  AdminVotersNewRoute: AdminVotersNewRoute,
  AdminCandidatesIndexRoute: AdminCandidatesIndexRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminContestantsIndexRoute: AdminContestantsIndexRoute,
  AdminElectionsIndexRoute: AdminElectionsIndexRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminOrganizationsIndexRoute: AdminOrganizationsIndexRoute,
  AdminPositionsIndexRoute: AdminPositionsIndexRoute,
  AdminVotersIndexRoute: AdminVotersIndexRoute,
  AdminCandidatesCandidateIdEditRoute: AdminCandidatesCandidateIdEditRoute,
  AdminElectionsElectionIdEditRoute: AdminElectionsElectionIdEditRoute,
  AdminElectionsElectionIdFeedRoute: AdminElectionsElectionIdFeedRoute,
  AdminElectionsElectionIdManageRoute: AdminElectionsElectionIdManageRoute,
  AdminPositionsPositionIdEditRoute: AdminPositionsPositionIdEditRoute,
  AdminVotersVoterIdEditRoute: AdminVotersVoterIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  ElectionsRoute: ElectionsRoute,
  StoreRoute: StoreRoute,
  TicketsRoute: TicketsRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  VoteCastRoute: VoteCastRoute,
  VoteElectionRoute: VoteElectionRoute,
  VoteReceiptAuditRoute: VoteReceiptAuditRoute,
  EventsIndexRoute: EventsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
  NomineeNomineeIdIndexRoute: NomineeNomineeIdIndexRoute,
  EventsEventIdCategoriesIndexRoute: EventsEventIdCategoriesIndexRoute,
  EventsEventIdCategoriesCategoryIdIndexRoute:
    EventsEventIdCategoriesCategoryIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
